POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3Rpa2F5dHRhamEiLCJpZCI6IjYwZTk2NjU3MDJhODNhNDhhOGFmMzc4OSIsImlhdCI6MTYyNTkxMTg0N30.3VrWFs7RwvZ0iT8P7cAUh2VrNpkJLyazyFdKpoJhUSM

{
    "title": "Random blog, random 2222222",
    "author": "Mr Bojanglez",
    "url": "www.iamfunny2.com",
    "likes": "123"
}