DELETE http://localhost:3003/api/blogs/60e972353251956121c6d332
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3Rpa2F5dHRhamEiLCJpZCI6IjYwZTk2NjU3MDJhODNhNDhhOGFmMzc4OSIsImlhdCI6MTYyNjA5ODc5MX0.JkCXigUgI1gDrg65xtMSbwv-H-O06xz1zPuOm3Nv2xY